# conf/validation/t_shopping_cv.yaml
# Используем нашу кастомную временную кросс-валидацию для надежной оценки.

_target_: src.validation.time_series.RollingTimeCV

# Имя колонки с номером дня
date_col: "date"

# Создадим 3 фолда для устойчивой оценки
n_splits: 3

# Длительность валидационной выборки - 7 дней, как в соревновании
valid_duration: 7

# Для GroupKFold и метрик ранжирования нужно знать, по какой колонке группировать.
# Мы добавляем этот параметр сюда, и train.py его подхватит.
group_col: ${globals.id_col}