# conf/model/rbf_svc.yaml
# Ключевые особенности SVM:
# Чувствительность к масштабированию: Признаки обязательно должны быть масштабированы (например, с помощью StandardScaler). 
#                                     SVM ищет "оптимальную улицу" между классами, и если один признак имеет диапазон, а другой, первый будет полностью 
#                                     доминировать при расчете расстояний.
# Вычислительная сложность: Обучение SVM (особенно с нелинейными ядрами, такими как rbf) имеет сложность между O(N²) и O(N³),
#                           где N — количество объектов. Это делает его очень медленным на датасетах размером > 10,000-50,000 строк. Для больших датасетов его использование может быть непрактичным.
_target_: src.models.sklearn_model.SklearnModel

# --- Параметры ---
model_class: "sklearn.svm.SVC"

params:
  # --- Ядро ---
  # 'rbf' (Radial Basis Function): Гауссово ядро. Позволяет строить
  # сложные, нелинейные границы.
  kernel: "rbf"
  
  # --- Основные гиперпараметры для RBF ---
  
  # `C`: параметр регуляризации. Контролирует компромисс между гладкостью
  # границы и правильностью классификации обучающих точек.
  C: 1.0
  
  # `gamma`: параметр ядра. Определяет, насколько "влияние" одной
  # обучающей точки распространяется на окружающее пространство.
  # 'scale': 1 / (n_features * X.var()) - хороший выбор по умолчанию.
  # 'auto': 1 / n_features.
  gamma: "scale"
  
  # --- Вероятности ---
  probability: true
  
  # --- Производительность ---
  # `cache_size`: размер кэша ядра в МБ. Увеличьте, если у вас много RAM.
  cache_size: 500

  # `max_iter`: -1 означает без ограничений.
  max_iter: -1

  random_state: ${globals.seed}